alias a='git add'
alias a.='git add .'
alias b='git checkout -'
alias d='git diff -w --ignore-blank-lines --color-words'
alias dc='git diff --cached'
alias s='git status --short --branch'
alias l='git log --graph --decorate --oneline'
alias c='git commit -m'
alias cm='git commit'
alias ca='git commit --amend'
alias p='git push'
alias bs='git branch | peco | pbcopy'
alias gco=git_checkout_with_search
alias gem=git_merge_with_search
alias nah=git_nah
alias u=git_sync_with_remote_head
alias e=emacs # 'emacsclient -c -a ""'
alias git='hub'
alias clang++='clang++ -std=c++0x'
alias c++='clang++'
alias ls='ls -alh'
alias rm='rmtrash'
alias sudo='sudo '
alias o='open'
alias j='autojump'
alias skim='open -a /Applications/Skim.app'
alias less='less -R'
alias t='tig'
alias scripts=list-scripts
alias k=kubectl
